spring.application.name=discovery-server
server.port=8761

# On rend le hostname flexible
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false