spring.application.name=config-server
server.port=8889

# Mode Native
spring.profiles.active=native
# Default location for IntelliJ, can be overridden by CONFIG_LOCATION in Docker
spring.cloud.config.server.native.search-locations=${CONFIG_LOCATION:file:../config-repo}

# Git Mode (Optional)
spring.cloud.config.server.git.uri=${CONFIG_GIT_URI:https://github.com/EventPlatform-Project/microservices-config.git}
spring.cloud.config.server.git.default-label=${CONFIG_GIT_BRANCH:main}
spring.cloud.config.server.git.clone-on-start=true

# Eureka Registration
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,refresh